// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYChP3xzrMiissBaHvIiHpHjrsyW1HhhI',
    appId: '1:897877392132:web:63920ffda870d3a079ae51',
    messagingSenderId: '897877392132',
    projectId: 'united-app-8771a',
    authDomain: 'united-app-8771a.firebaseapp.com',
    storageBucket: 'united-app-8771a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx9kj8iHCN_w23UP7WqECvAMw_ZnRP21Y',
    appId: '1:897877392132:android:d6fe7f4eaf3567d479ae51',
    messagingSenderId: '897877392132',
    projectId: 'united-app-8771a',
    storageBucket: 'united-app-8771a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYChP3xzrMiissBaHvIiHpHjrsyW1HhhI',
    appId: '1:897877392132:web:9d67391bd745cf5079ae51',
    messagingSenderId: '897877392132',
    projectId: 'united-app-8771a',
    authDomain: 'united-app-8771a.firebaseapp.com',
    storageBucket: 'united-app-8771a.firebasestorage.app',
  );
}
